name: Trigger auto deployment for aapowell-contosoair

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aapowell-contosoair-AutoDeployTrigger-fb01b817-011d-4635-9e3b-0d7ca0bf2669.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca787c8c9766acr.azurecr.io
          username: ${{ secrets.AAPOWELLCONTOSOAIR_REGISTRY_USERNAME }}
          password: ${{ secrets.AAPOWELLCONTOSOAIR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca787c8c9766acr.azurecr.io/aapowell-contosoair:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AAPOWELLCONTOSOAIR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n aapowell-contosoair -g aapowell_rg_5572 --server ca787c8c9766acr.azurecr.io --username  ${{ secrets.AAPOWELLCONTOSOAIR_REGISTRY_USERNAME }} --password ${{ secrets.AAPOWELLCONTOSOAIR_REGISTRY_PASSWORD }}
            az containerapp update -n aapowell-contosoair -g aapowell_rg_5572 --image ca787c8c9766acr.azurecr.io/aapowell-contosoair:${{ github.sha }}
